# Generated by Django 3.0.8 on 2020-09-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
