# Generated by Django 3.1.1 on 2020-09-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='request.user', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='lord.jpg', null=True, upload_to=''),
        ),
    ]
