# Generated by Django 3.1.1 on 2020-09-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200924_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
