# Generated by Django 3.1.1 on 2020-09-27 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200924_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_time',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='posts',
            new_name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
